# Generated by Django 5.0.7 on 2024-07-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_zipcode_order_payment_intent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place',
            new_name='postcode',
        ),
    ]
